### ISSUE TITLE
esp-idf version 

### ISSUE THREAD

**Issue by Heusini** [particle-iot/esp32-ncp-firmware#20]
What version of esp-idf was used to compile the firmware?
I used the most recent one but got compiler errors.

**Comment by avtolstoy** [comment]
See `esp32-at` submodule for info on which version of `esp-idf` it uses: https://github.com/particle-iot/esp32-ncp-firmware/tree/master/third_party

At the time of writing the current `master` uses the following revision of our IDF fork: https://github.com/particle-iot/esp-idf/tree/c8010d24605a731ee05d83317f099c5f58c1ce81

**Comment by Heusini** [comment]
ah thanks.
